name: Deployment of Application

on:
  push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Commit & Push themeMode changes (if any)
        run: |
          git config --global user.name "codewithajoydas"
          git config --global user.email "codewithajoydas@gmail.com"
          git add .
          if git diff --cached --quiet; then
            echo "✅ No changes to commit"
          else
            git commit -m "♻️ Toggle theme mode"
            git push
          fi

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: vercel --prod --token=$VERCEL_TOKEN --yes
