name: Deployment of Application

push:
    branches:
      - main

permissions:
  contents: write  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Commit & Push
        run: |
        
          git config --global user.name "codewithajoydas"
          git config --global user.email "codewithajoydas@gmail.com"
          git add .
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "♻️ Toggle theme mode"
            git push
          fi
      - name: vercel
        run: |
           npm i -g vercel
           vercel